name: Docker Image CI - Envoy 1.32

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ "release-1.32" ]
  pull_request:
    branches: [ "release-1.32" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  ENVOY_VERSION: 1.32.2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout Envoy repository
      uses: actions/checkout@v3
      with:
        repository: envoyproxy/envoy
        ref: v${{ env.ENVOY_VERSION }}
        path: envoy
        fetch-depth: 1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Prepare Envoy Build
      run: |
        cd envoy
        ./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--define tcmalloc=gperftools" ./ci/do_ci.sh bazel.release.server_only'
      working-directory: ${{ github.workspace }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: envoy
        platforms: linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/envoy:1.32.2
          ${{ secrets.DOCKERHUB_USERNAME }}/envoy:latest

