name: Envoy Docker Publish

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

# Ensures only one workflow runs at a time for a given branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Explicitly specify arm64 architecture
    strategy:
      matrix:
        platform: [arm64]

    steps:
    # Checkout the Envoy repository
    - name: Checkout Envoy Repository
      uses: actions/checkout@v4
      with:
        repository: 'envoyproxy/envoy'
        # You might want to specify a specific ref/branch/tag if needed
        # ref: 'main'

    # Setup Docker buildx for multi-architecture support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    # Optional: Login to Docker registry if you plan to push
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Run the Envoy Docker build script
    - name: Run Envoy Docker Build Script
      run: |
        chmod +x ./ci/run_envoy_docker.sh
        ./ci/run_envoy_docker.sh 'BAZEL_BUILD_EXTRA_OPTIONS="--define tcmalloc=gperftools" ./ci/do_ci.sh bazel.release.server_only'
      # Note: This assumes the script is present in the checked out repository
      # If the script requires specific setup or dependencies, you might need additional steps

    # Optionally, you could add a step to build and push the Docker image
    # - name: Build and Push Docker Image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     platforms: linux/arm64
    #     push: true
    #     tags: your-docker-image-tag

